# Generated by Django 2.0.1 on 2018-02-05 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('album_title', models.CharField(max_length=30)),
                ('album_logo', models.FileField(default='', upload_to='')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
