# Generated by Django 2.0.1 on 2018-01-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
