# Generated by Django 2.0.1 on 2018-01-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180125_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='file_type',
        ),
        migrations.AddField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
