# Generated by Django 2.0.1 on 2018-01-29 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180129_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='songs',
            name='file_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
